name: 'Setup ttoss Environment'
description: 'Sets up Node.js, pnpm, cache, and installs dependencies for ttoss monorepo'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '24'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      id: pnpm-install
      with:
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
    - name: Install Playwright browsers (for Storybook llms.txt generation)
      shell: bash
      run: |
        if pnpm list @fluentui/storybook-llms-extractor --depth -1 > /dev/null 2>&1; then
          echo "Installing Playwright Chromium for llms.txt generation..."
          if pnpm exec playwright --version > /dev/null 2>&1; then
            pnpm exec playwright install --with-deps chromium
          else
            echo "Playwright CLI not found in dependencies, skipping Playwright installation"
          fi
        else
          echo "Storybook llms extractor not found, skipping Playwright installation"
        fi
