AWSTemplateFormatVersion: '2010-09-09'

Description: ttoss challenge DynamoDB table

Resources:
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: 'pk'
          AttributeType: 'S'
        - AttributeName: 'sk'
          AttributeType: 'S'
        - AttributeName: 'rating'
          AttributeType: 'N'
      BillingMode: 'PAY_PER_REQUEST'
      DeletionProtectionEnabled: true
      KeySchema:
        - AttributeName: 'pk'
          KeyType: 'HASH'
        - AttributeName: 'sk'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: 'sk-rating-index'
          KeySchema:
            - AttributeName: 'sk'
              KeyType: 'HASH'
            - AttributeName: 'rating'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL

Outputs:
  DynamoDBTableArn:
    Value: !GetAtt DynamoDBTable.Arn
    Description: ARN of the DynamoDB Table
    Export:
      Name: !Sub '${AWS::StackName}:DynamoDBTableArn'

  DynamoDBTableName:
    Value: !Ref DynamoDBTable
    Description: Name of the DynamoDB Table
    Export:
      Name: !Sub '${AWS::StackName}:DynamoDBTableName'
