import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  product: [{ type: 'autogenerated', dirName: 'product' }],
  design: [{ type: 'autogenerated', dirName: 'design' }],
  engineering: [{ type: 'autogenerated', dirName: 'engineering' }],
  ai: [{ type: 'autogenerated', dirName: 'ai' }],
  challenge: [{ type: 'autogenerated', dirName: 'challenge' }],
  carlin: [{ type: 'autogenerated', dirName: 'carlin' }],
  modules: [{ type: 'autogenerated', dirName: 'modules' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
