export { authMiddleware } from './authMiddleware';
export {
  createEmailAuthHandlers,
  emailAuth,
  type EmailAuthDelivery,
  type EmailAuthErrorCode,
  emailAuthErrorCodes,
  type EmailAuthHandler,
  type EmailAuthHandlers,
  type EmailAuthHooks,
  type EmailAuthMode,
  type EmailAuthOptions,
  type EmailAuthPaths,
  type EmailAuthSession,
  type EmailAuthTtl,
  type EmailAuthUser,
  type EmailAuthUserStore,
  type EmailCodeOptions,
  normalizeEmail,
  type OneTimeTokenPurpose,
  type OneTimeTokenStore,
  type PasswordOptions,
  type RequestRateLimit,
  type RequestRateLimitStore,
  type StoredOneTimeToken,
} from './emailAuth';
export {
  type AuthCodeStore,
  type AuthorizeRequest,
  type ClientStore,
  createOAuthHandlers,
  createProtectedResourceMetadataMiddleware,
  getWwwAuthenticateHeader,
  type IssuedTokens,
  type IssueTokensArgs,
  type OAuthClient,
  type OAuthClientMetadata,
  type OAuthHandlers,
  oauthServer,
  type OAuthServerOptions,
  type OnAuthorizeArgs,
  type OnAuthorizeResult,
  type OnRefreshTokenArgs,
  type OnRefreshTokenResult,
  type StoredAuthorizationCode,
} from './oauthServer';
export { isOriginAllowed } from './origin';
export { requireAuth } from './requireAuth';
export type {
  ApiTokenOptions,
  AuthenticatedUser,
  AuthMiddlewareOptions,
  AuthStrategy,
  JwtOptions,
  OAuthOptions,
  SystemOptions,
} from './types';
