/**
 * generate-barrel.ts — Auto-generates `src/index.ts` from filesystem discovery.
 *
 * Scans `src/components/` and `src/composites/` directories and produces
 * the public barrel file. Exports only consumer-facing API (Component + Props type),
 * NOT internal exports like contractConfig or componentMeta.
 *
 * Convention: each component module's default export is the component itself,
 * named identically to the directory (e.g. `Button` from `Button/`).
 *
 * **When to run:**
 *   pnpm run generate:barrel
 *
 * Run after:
 *   - Adding or removing a component or composite
 */

import * as fs from 'node:fs';
import { createRequire } from 'node:module';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const srcDir = path.resolve(__dirname, '../src');
const indexPath = path.resolve(srcDir, 'index.ts');

// ---------------------------------------------------------------------------
// Discovery
// ---------------------------------------------------------------------------

const discoverDirs = (baseDir: string): string[] => {
  if (!fs.existsSync(baseDir)) return [];
  return fs
    .readdirSync(baseDir, { withFileTypes: true })
    .filter((d) => {
      return d.isDirectory();
    })
    .map((d) => {
      return d.name;
    })
    .sort();
};

const componentDirs = discoverDirs(path.resolve(srcDir, 'components'));
const compositeDirs = discoverDirs(path.resolve(srcDir, 'composites'));

// ---------------------------------------------------------------------------
// Detect exports per component module
// ---------------------------------------------------------------------------

/**
 * Reads a component module and finds its public export names.
 * Public exports are:
 *   - The component itself (PascalCase name matching dir, e.g. `Button`)
 *   - Types ending in `Props` or `Size` (e.g. `ButtonProps`, `ButtonSize`)
 * Internal exports (contractConfig, componentMeta, compositeConfig, compositeMeta) are excluded.
 */
const getPublicExports = (
  modulePath: string,
  dirName: string
): { values: string[]; types: string[] } => {
  const mod = require(modulePath) as Record<string, unknown>;
  const allKeys = Object.keys(mod);

  const internalSuffixes = [
    'ContractConfig',
    'ComponentMeta',
    'CompositeMeta',
    'CompositeConfig',
  ];

  const values: string[] = [];
  const types: string[] = [];

  for (const key of allKeys) {
    // Skip internal exports
    if (
      internalSuffixes.some((s) => {
        return key.endsWith(s);
      })
    )
      continue;

    // The component itself is the PascalCase dir name (Button, Input, etc.)
    if (key === dirName) {
      values.push(key);
      continue;
    }

    // Type exports can't be detected at runtime via require (they're erased).
    // We'll detect them by scanning the source file.
  }

  // Scan source for `export type` or `export interface` declarations
  const srcFile = fs.readFileSync(modulePath, 'utf-8');
  const typeExportRe = /export\s+(?:type|interface)\s+(\w+)/g;
  let match;
  while ((match = typeExportRe.exec(srcFile)) !== null) {
    const name = match[1]!;
    if (
      !internalSuffixes.some((s) => {
        return name.endsWith(s);
      })
    ) {
      types.push(name);
    }
  }

  return { values, types };
};

// ---------------------------------------------------------------------------
// Generate
// ---------------------------------------------------------------------------

const lines: string[] = [];

for (const dir of componentDirs) {
  const modulePath = path.resolve(srcDir, 'components', dir, `${dir}.tsx`);
  if (!fs.existsSync(modulePath)) continue;

  const { values, types } = getPublicExports(modulePath, dir);
  const relPath = `./components/${dir}/${dir}`;

  if (values.length > 0) {
    lines.push(`export { ${values.join(', ')} } from '${relPath}';`);
  }
  if (types.length > 0) {
    lines.push(`export type { ${types.join(', ')} } from '${relPath}';`);
  }
}

for (const dir of compositeDirs) {
  const modulePath = path.resolve(srcDir, 'composites', dir, `${dir}.tsx`);
  if (!fs.existsSync(modulePath)) continue;

  const { values, types } = getPublicExports(modulePath, dir);
  const relPath = `./composites/${dir}/${dir}`;

  if (values.length > 0) {
    lines.push(`export { ${values.join(', ')} } from '${relPath}';`);
  }
  if (types.length > 0) {
    lines.push(`export type { ${types.join(', ')} } from '${relPath}';`);
  }
}

// ---------------------------------------------------------------------------
// Assemble
// ---------------------------------------------------------------------------

const output = `/**
 * @ttoss/ui2 — Public component exports.
 *
 * THIS FILE IS AUTO-GENERATED by scripts/generate-barrel.ts.
 * DO NOT EDIT MANUALLY.
 * Regenerate: pnpm run generate:barrel
 *
 * Import styles separately:
 *   import '@ttoss/ui2/styles.css';
 *
 * For tooling, AI agents, and contract tests, import the model:
 *   import { resolveTokens } from '@ttoss/ui2/model';
 */
${lines.join('\n')}
`;

fs.writeFileSync(indexPath, output, 'utf-8');
// eslint-disable-next-line no-console
console.log(
  `index.ts generated — ${componentDirs.length} components, ${compositeDirs.length} composites`
);
