/**
 * Setup monorepo configuration following ttoss guidelines.
 * Guide: https://ttoss.dev/docs/config/README.md
 */
import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { createFile } from './utils';

const createPackageJsonIfNotExists = ({ dir }: { dir: string }) => {
  const packageJsonPath = path.join(dir, 'package.json');

  if (fs.existsSync(packageJsonPath)) {
    // eslint-disable-next-line no-console
    console.log('- package.json already exists');
    return false;
  }

  // eslint-disable-next-line no-console
  console.log('📦 Creating package.json...');

  const dirName = path.basename(dir);
  const packageJson = {
    name: dirName,
    version: '0.0.0',
    private: true,
    type: 'module',
    scripts: {},
    devDependencies: {},
  };

  fs.writeFileSync(
    packageJsonPath,
    JSON.stringify(packageJson, null, 2) + '\n'
  );

  // eslint-disable-next-line no-console
  console.log('✓ Created package.json');
  return true;
};

const prettierrcConfig = `import { prettierConfig } from '@ttoss/config';

export default prettierConfig();
`;

const eslintConfig = `import ttossEslintConfig from '@ttoss/eslint-config';

export default [...ttossEslintConfig];
`;

const commitlintConfig = `import { commitlintConfig } from '@ttoss/config';

export default commitlintConfig();
`;

const lintstagedConfig = `import { lintstagedConfig } from '@ttoss/config';

export default lintstagedConfig();
`;

const syncpackrcConfig = `import { syncpackConfig } from '@ttoss/config';

export default syncpackConfig();
`;

const lernaConfig = `{
  "$schema": "node_modules/@lerna-lite/cli/schemas/lerna-schema.json",
  "version": "independent",
  "npmClient": "pnpm",
  "stream": true,
  "command": {
    "publish": {
      "allowBranch": "main",
      "noPrivate": true
    },
    "version": {
      "conventionalCommits": true,
      "createRelease": "github",
      "message": "chore(release): publish packages",
      "syncWorkspaceLock": true,
      "allowPeerDependenciesUpdate": true
    }
  },
  "ignoreChanges": ["**/__fixtures__/**", "**/tests/**"],
  "packages": ["packages/*"]
}
`;

const pnpmWorkspaceConfig = `packages:
  - 'packages/*'
`;

const commitMsgHook = `pnpm commitlint --edit
`;

const preCommitHook = `pnpm lint-staged
pnpm syncpack:list
`;

const gitignoreConfig = `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)
report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage
*.lcov

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# TypeScript cache
*.tsbuildinfo

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Microbundle cache
.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env
.env.test

# parcel-bundler cache (https://parceljs.org/)
.cache

# Next.js build output
.next

# Nuxt.js build / generate output
.nuxt
dist

# Gatsby files
.cache/
# Comment in the public line in if your project uses Gatsby and *not* Next.js
# https://nextjs.org/blog/next-9-1#public-directory-support
# public

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless/

# FuseBox cache
.fusebox/

# DynamoDB Local files
.dynamodb/

# TernJS port file
.tern-port

build/
.build/
dist/
out/
node_modules/
.cache/
tmp_*
storybook-static/
package-lock.json
yarn.lock
github-app/
.carlin/
.vscode
.turbo
**/i18n/compiled/
**/i18n/missing/
**/i18n/unused/
tsup.config.bundled*.mjs
`;

const npmrcConfig = `enable-pre-post-scripts=true
engine-strict=true
public-hoist-pattern[]=*eslint*
public-hoist-pattern[]=*prettier*
# https://github.com/pnpm/pnpm/issues/4920#issuecomment-1226724790
public-hoist-pattern[]=@types*
`;

const installEslintPrettierDependencies = ({ dir }: { dir: string }) => {
  const packageJsonPath = path.join(dir, 'package.json');

  if (!fs.existsSync(packageJsonPath)) {
    // eslint-disable-next-line no-console
    console.log('⚠ package.json not found, skipping dependency installation');
    return false;
  }

  // eslint-disable-next-line no-console
  console.log(
    '\n📦 Installing ESLint, Prettier, and @ttoss/config dependencies...'
  );

  try {
    execSync(
      'pnpm add -Dw eslint prettier @ttoss/eslint-config @ttoss/config',
      {
        cwd: dir,
        stdio: 'inherit',
      }
    );
    // eslint-disable-next-line no-console
    console.log(
      '✓ Installed eslint, prettier, @ttoss/eslint-config, and @ttoss/config'
    );
    return true;
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('✗ Failed to install dependencies:', error);
    // eslint-disable-next-line no-console
    console.log('  You can install them manually with:');
    // eslint-disable-next-line no-console
    console.log(
      '  pnpm add -Dw eslint prettier @ttoss/eslint-config @ttoss/config'
    );
    return false;
  }
};

const installHuskyDependencies = ({ dir }: { dir: string }) => {
  const packageJsonPath = path.join(dir, 'package.json');

  if (!fs.existsSync(packageJsonPath)) {
    // eslint-disable-next-line no-console
    console.log('⚠ package.json not found, skipping dependency installation');
    return false;
  }

  // eslint-disable-next-line no-console
  console.log('\n📦 Installing Husky, commitlint, and lint-staged...');

  try {
    execSync('pnpm add -Dw husky @commitlint/cli lint-staged', {
      cwd: dir,
      stdio: 'inherit',
    });
    // eslint-disable-next-line no-console
    console.log('✓ Installed husky, @commitlint/cli, and lint-staged');
    return true;
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('✗ Failed to install dependencies:', error);
    // eslint-disable-next-line no-console
    console.log('  You can install them manually with:');
    // eslint-disable-next-line no-console
    console.log('  pnpm add -Dw husky @commitlint/cli lint-staged');
    return false;
  }
};

const installLernaDependencies = ({ dir }: { dir: string }) => {
  const packageJsonPath = path.join(dir, 'package.json');

  if (!fs.existsSync(packageJsonPath)) {
    // eslint-disable-next-line no-console
    console.log('⚠ package.json not found, skipping dependency installation');
    return false;
  }

  // eslint-disable-next-line no-console
  console.log('\n📦 Installing Lerna dependencies...');

  try {
    execSync(
      'pnpm add -Dw @lerna-lite/cli @lerna-lite/version @lerna-lite/changed @lerna-lite/list',
      {
        cwd: dir,
        stdio: 'inherit',
      }
    );
    // eslint-disable-next-line no-console
    console.log('✓ Installed @lerna-lite packages');
    return true;
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('✗ Failed to install dependencies:', error);
    // eslint-disable-next-line no-console
    console.log('  You can install them manually with:');
    // eslint-disable-next-line no-console
    console.log(
      '  pnpm add -Dw @lerna-lite/cli @lerna-lite/version @lerna-lite/changed @lerna-lite/list'
    );
    return false;
  }
};

const installSyncpackDependency = ({ dir }: { dir: string }) => {
  const packageJsonPath = path.join(dir, 'package.json');

  if (!fs.existsSync(packageJsonPath)) {
    // eslint-disable-next-line no-console
    console.log('⚠ package.json not found, skipping dependency installation');
    return false;
  }

  // eslint-disable-next-line no-console
  console.log('\n📦 Installing Syncpack...');

  try {
    execSync('pnpm add -Dw syncpack', {
      cwd: dir,
      stdio: 'inherit',
    });
    // eslint-disable-next-line no-console
    console.log('✓ Installed syncpack');
    return true;
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('✗ Failed to install dependency:', error);
    // eslint-disable-next-line no-console
    console.log('  You can install it manually with:');
    // eslint-disable-next-line no-console
    console.log('  pnpm add -Dw syncpack');
    return false;
  }
};

const updatePackageJsonWithMonorepoScripts = ({ dir }: { dir: string }) => {
  const packageJsonPath = path.join(dir, 'package.json');

  if (!fs.existsSync(packageJsonPath)) {
    // eslint-disable-next-line no-console
    console.log('⚠ package.json not found, skipping script updates');
    return false;
  }

  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

  packageJson.scripts = packageJson.scripts || {};

  let updated = false;

  // Add syncpack scripts
  if (!packageJson.scripts['syncpack:fix']) {
    packageJson.scripts['syncpack:fix'] = 'syncpack fix-mismatches';
    // eslint-disable-next-line no-console
    console.log('✓ Added "syncpack:fix" script to package.json');
    updated = true;
  }

  if (!packageJson.scripts['syncpack:list']) {
    packageJson.scripts['syncpack:list'] = 'syncpack list-mismatches';
    // eslint-disable-next-line no-console
    console.log('✓ Added "syncpack:list" script to package.json');
    updated = true;
  }

  if (updated) {
    fs.writeFileSync(
      packageJsonPath,
      JSON.stringify(packageJson, null, 2) + '\n'
    );
    return true;
  } else {
    // eslint-disable-next-line no-console
    console.log('- Syncpack scripts already exist in package.json');
    return false;
  }
};

const updatePackageJsonWithHuskyScript = ({ dir }: { dir: string }) => {
  const packageJsonPath = path.join(dir, 'package.json');

  if (!fs.existsSync(packageJsonPath)) {
    // eslint-disable-next-line no-console
    console.log('⚠ package.json not found, skipping script updates');
    return false;
  }

  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

  packageJson.scripts = packageJson.scripts || {};

  // Add prepare script for husky if it doesn't exist
  if (!packageJson.scripts.prepare) {
    packageJson.scripts.prepare = 'husky';
    // eslint-disable-next-line no-console
    console.log('✓ Added "prepare" script to package.json');

    fs.writeFileSync(
      packageJsonPath,
      JSON.stringify(packageJson, null, 2) + '\n'
    );
    return true;
  } else {
    // eslint-disable-next-line no-console
    console.log('- "prepare" script already exists in package.json');
    return false;
  }
};

const setupHusky = ({ dir }: { dir: string }) => {
  // eslint-disable-next-line no-console
  console.log('\n🐶 Setting up Husky...');

  try {
    // Run prepare script to install husky
    execSync('pnpm run prepare', {
      cwd: dir,
      stdio: 'inherit',
    });
    // eslint-disable-next-line no-console
    console.log('✓ Husky installed');

    // Create commit-msg hook
    createFile({
      filePath: path.join(dir, '.husky/commit-msg'),
      content: commitMsgHook,
    });

    // Create pre-commit hook
    createFile({
      filePath: path.join(dir, '.husky/pre-commit'),
      content: preCommitHook,
    });

    return true;
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('✗ Failed to setup Husky:', error);
    // eslint-disable-next-line no-console
    console.log('  You can set it up manually by following the README:');
    // eslint-disable-next-line no-console
    console.log(
      '  https://github.com/ttoss/ttoss/blob/main/packages/config/README.md'
    );
    return false;
  }
};

export const setupMonorepo = ({ dir }: { dir: string }) => {
  const absoluteDir = path.resolve(dir);

  // eslint-disable-next-line no-console
  console.log(`\n🚀 Setting up monorepo configuration in: ${absoluteDir}\n`);

  // Create package.json if it doesn't exist
  createPackageJsonIfNotExists({ dir: absoluteDir });

  // eslint-disable-next-line no-console
  console.log('\n📝 Creating configuration files...\n');

  // Create pnpm-workspace.yaml file first (required before installing workspace dependencies)
  createFile({
    filePath: path.join(absoluteDir, 'pnpm-workspace.yaml'),
    content: pnpmWorkspaceConfig,
  });

  // Create ESLint and Prettier config files
  createFile({
    filePath: path.join(absoluteDir, '.prettierrc.js'),
    content: prettierrcConfig,
  });

  createFile({
    filePath: path.join(absoluteDir, 'eslint.config.js'),
    content: eslintConfig,
  });

  // Install ESLint and Prettier dependencies
  const eslintInstalled = installEslintPrettierDependencies({
    dir: absoluteDir,
  });

  // Create commitlint and lint-staged config files
  createFile({
    filePath: path.join(absoluteDir, '.commitlintrc.js'),
    content: commitlintConfig,
  });

  createFile({
    filePath: path.join(absoluteDir, '.lintstagedrc.js'),
    content: lintstagedConfig,
  });

  // Install Husky dependencies
  const huskyInstalled = installHuskyDependencies({ dir: absoluteDir });

  // Update package.json with prepare script
  updatePackageJsonWithHuskyScript({ dir: absoluteDir });

  // Setup Husky hooks
  if (huskyInstalled) {
    setupHusky({ dir: absoluteDir });
  }

  // Create lerna and syncpack config files
  createFile({
    filePath: path.join(absoluteDir, 'lerna.json'),
    content: lernaConfig,
  });

  createFile({
    filePath: path.join(absoluteDir, '.syncpackrc.js'),
    content: syncpackrcConfig,
  });

  // Create .gitignore file
  createFile({
    filePath: path.join(absoluteDir, '.gitignore'),
    content: gitignoreConfig,
  });

  // Create .npmrc file
  createFile({
    filePath: path.join(absoluteDir, '.npmrc'),
    content: npmrcConfig,
  });

  // Install Lerna and Syncpack dependencies
  const lernaInstalled = installLernaDependencies({ dir: absoluteDir });
  const syncpackInstalled = installSyncpackDependency({ dir: absoluteDir });

  // Update package.json with monorepo scripts
  updatePackageJsonWithMonorepoScripts({ dir: absoluteDir });

  // eslint-disable-next-line no-console
  console.log('\n✅ Monorepo setup complete!');
  // eslint-disable-next-line no-console
  console.log('\nConfiguration files created:');
  // eslint-disable-next-line no-console
  console.log('  - .prettierrc.js');
  // eslint-disable-next-line no-console
  console.log('  - .commitlintrc.js');
  // eslint-disable-next-line no-console
  console.log('  - .lintstagedrc.js');
  // eslint-disable-next-line no-console
  console.log('  - .gitignore');
  // eslint-disable-next-line no-console
  console.log('  - lerna.json');
  // eslint-disable-next-line no-console
  console.log('  - .syncpackrc.js');
  // eslint-disable-next-line no-console
  console.log('  - pnpm-workspace.yaml');
  // eslint-disable-next-line no-console
  console.log('  - .npmrc');

  if (huskyInstalled) {
    // eslint-disable-next-line no-console
    console.log('  - .husky/commit-msg (commitlint hook)');
    // eslint-disable-next-line no-console
    console.log('  - .husky/pre-commit (lint-staged hook)');
  }

  // eslint-disable-next-line no-console
  console.log('\nNext steps:');
  // eslint-disable-next-line no-console
  console.log(
    '1. Update pnpm-workspace.yaml "packages" field to match your monorepo structure'
  );
  // eslint-disable-next-line no-console
  console.log(
    '2. Update lerna.json "packages" field to match your monorepo structure'
  );
  // eslint-disable-next-line no-console
  console.log('3. Run "pnpm syncpack:list" to check for version mismatches');
  // eslint-disable-next-line no-console
  console.log('4. Commit your changes to test the hooks');
  // eslint-disable-next-line no-console
  console.log('5. Run "pnpm lint" to check your code');

  if (!eslintInstalled) {
    // eslint-disable-next-line no-console
    console.log(
      '6. Install ESLint dependencies manually: pnpm add -Dw eslint prettier @ttoss/eslint-config @ttoss/config'
    );
  }

  if (!huskyInstalled) {
    // eslint-disable-next-line no-console
    console.log(
      '7. Install Husky dependencies manually: pnpm add -Dw husky @commitlint/cli lint-staged'
    );
    // eslint-disable-next-line no-console
    console.log('8. Run "pnpm run prepare" to initialize Husky');
  }

  if (!lernaInstalled) {
    // eslint-disable-next-line no-console
    console.log(
      '9. Install Lerna dependencies manually: pnpm add -Dw @lerna-lite/cli @lerna-lite/version @lerna-lite/changed @lerna-lite/list'
    );
  }

  if (!syncpackInstalled) {
    // eslint-disable-next-line no-console
    console.log('10. Install Syncpack manually: pnpm add -Dw syncpack');
  }

  // eslint-disable-next-line no-console
  console.log('');
};
